# Generated by Django 5.2.7 on 2026-04-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
