# Generated by Django 5.2.7 on 2026-03-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        ('licenses', '0002_alter_prolicense_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicebackup',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='devicebackup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='devicebackup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01T00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicebackup',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicebackup',
            name='backup_data',
            field=models.JSONField(default=dict, help_text='Full export of the Flutter SQLite database as JSON'),
        ),
        migrations.AlterField(
            model_name='devicebackup',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='licenses.prolicense'),
        ),
    ]
