# Generated by Django 5.2.7 on 2026-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique hardware ID from device_info_plus', max_length=200, unique=True)),
                ('paystack_reference', models.CharField(help_text='Verified Paystack transaction reference', max_length=200, unique=True)),
                ('jwt_token', models.TextField(help_text='The latest signed JWT issued to this device')),
                ('is_active', models.BooleanField(default=True)),
                ('amount_paid', models.IntegerField(help_text='Amount paid in minor units (e.g. kobo/cents)')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
