# Generated by Django 5.2.7 on 2026-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prolicense',
            name='amount_paid',
            field=models.IntegerField(default=0, help_text='Amount paid in minor units (e.g. kobo/cents)'),
        ),
        migrations.AlterField(
            model_name='prolicense',
            name='jwt_token',
            field=models.TextField(default='', help_text='The latest signed JWT issued to this device'),
        ),
    ]
